<script setup>
defineProps({
  code: {
    type: Boolean,
    default: true
  }
})

</script>

<template>
  <div class="loading" v-if="code">
    <div class="loadingio-spinner-spinner-nq4q5u6dq7r">
      <div class="ldio-x2uulkbinbj">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <p>拼命加载中</p>
      </div>
    </div>
  </div>
  <div v-else class="error">
    <el-result icon="error" title="获取数据失败" sub-title="请点击标签页重新获取数据">
    </el-result>
  </div>

</template>

<style scoped lang='scss'>
@keyframes ldio-x2uulkbinbj {
  0% {
    opacity: 1
  }

  100% {
    opacity: 0
  }
}

.loading {
  width: 100%;
  height: 800px;
}

.error {
  width: 100%;
  height: 800px;
  margin-top: 250px;
}

.ldio-x2uulkbinbj div {
  left: 45px;
  top: 40px;
  position: absolute;
  animation: ldio-x2uulkbinbj linear 1s infinite;
  background: #27ba9b;
  width: 12px;
  height: 24px;
  border-radius: 6px / 12px;
  transform-origin: 6px 52px;
}

.ldio-x2uulkbinbj div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.9166666666666666s;
  background: #27ba9b;
}

.ldio-x2uulkbinbj div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.8333333333333334s;
  background: #27ba9b;
}

.ldio-x2uulkbinbj div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.75s;
  background: #27ba9b;
}

.ldio-x2uulkbinbj div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.6666666666666666s;
  background: #27ba9b;
}

.ldio-x2uulkbinbj div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.5833333333333334s;
  background: #27ba9b;
}

.ldio-x2uulkbinbj div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.5s;
  background: #27ba9b;
}

.ldio-x2uulkbinbj div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.4166666666666667s;
  background: #27ba9b;
}

.ldio-x2uulkbinbj div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.3333333333333333s;
  background: #27ba9b;
}

.ldio-x2uulkbinbj div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.25s;
  background: #27ba9b;
}

.ldio-x2uulkbinbj div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.16666666666666666s;
  background: #27ba9b;
}

.ldio-x2uulkbinbj div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.08333333333333333s;
  background: #27ba9b;
}

.ldio-x2uulkbinbj div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: #27ba9b;
}

.loadingio-spinner-spinner-nq4q5u6dq7r {
  width: 100%;
  height: 100%;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}

.ldio-x2uulkbinbj {
  width: 100%;
  height: 100%;
  top: 30%;
  left: 45%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0;
  /* see note above */
}

.ldio-x2uulkbinbj div {
  box-sizing: content-box;
}

p {
  position: absolute;
  top: 160px;
  left: 12px;
  font-size: 16px;
}

/* [ldio] generated by https://loading.io */
</style>